### ISSUE TITLE
Training ,Model and inference code

### ISSUE THREAD

**Issue by abhigoku10** [SRainGit/CAE-LO#1]
@SRainGit hi thanks for wonderful work , is it possible to share the pre-trained model with training and inference pipeline 
THnaks in advance

**Comment by SRainGit** [comment]
> @SRainGit hi thanks for wonderful work , is it possible to share the pre-trained model with training and inference pipeline
> THnaks in advance

Hi, sorry for the late reply, and thank you for your interest! We are considering to release the pre-trained models at first. But actually, to get them work, it also depends on the preprocessing code and the postprocessing code.

**Comment by SRainGit** [comment]
Now the trained models and all the codes are available.
