### ISSUE TITLE
Demo data does not contain ground truth poses

### ISSUE THREAD

**Issue by nanaBaah** [SRainGit/CAE-LO#10]
I have 2 question:

1. Can i get a snippet of the folder structure for the project. Maybe a tree format of it?

2. The DemoData does not contain all the snippet of the data required to run the code.
Can I get the data for poses, poses__, poses___ ? and any other sample data you can share.

Thanks in advance

**Comment by SRainGit** [comment]
Yeah, DemoData doesn't show the whole folder structure, but other folders like 'KeyPts' and 'VoxelModel' etc.,  are just under the same base folder with 'Features'. A tree structure will be:
```
sequences
--00
----Features
----Features-3DFeatNet
----Features-USIP
----InlierIdx
----KeyPts
----RefinenmentData
----SphericalRing
----velodyne
----VoxelModel
----calib_.txt (removed texts from the original calib.txt)
--01
----......
--02
......
```

DemoData is just to visualize the matching comparison. Actually running the code only needs the benchmark data from KITTI.
`poses` is the ground truth, and you can download it from KITTI website;
`poses_` is the initial odometry generated by frame-by-frame matching;
`poses__` is the de-jumped poses of `poses_` (not shown in the paper, but you can check the code, very simple);
`poses___` is  refined poses based on `poses__`;
To get the refined poses, you need to run through the above steps.
The data of `poses___`, please see the second item of section 'Notes'. As for the data of `pose_` and `poses__`, I didn't backup them at the time I uploaded my result to KITTI. And then they were covered by my later results. But it is not important. You can check the `poses_` of 00 and 01 in DemoData.
