### ISSUE TITLE
GetKeyPtsAndPatchesFromKeyPts function cannot be found in RefinePoses.py

### ISSUE THREAD

**Issue by nanaBaah** [SRainGit/CAE-LO#12]
I cannot find GetKeyPtsAndPatchesFromKeyPts functionality that is stated in the RefinePose.py

![image](https://user-images.githubusercontent.com/12661590/99256120-32677f80-2815-11eb-8d7a-d58d1fa2c39a.png)

Please help me add this function or locate it. Thanks in advance

**Comment by SRainGit** [comment]
The functions of `GetKeyPtsAndPatchesFromKeyPts ` and `ReExtractFeatures` were designed as a part of my previous refine solution. Now they are deprecated.
Sorry for this, I thought I removed almost all the undeeded codes. But actually, you can find out that nothing calls these two functions in this repository.
