### ISSUE TITLE
Prediction of LiDAR pointcloud odometry

### ISSUE THREAD

**Issue by nanaBaah** [SRainGit/CAE-LO#13]
I wish to give as input a sequence of point cloud data to your AI model and then the model outputs a sequence of final odometry values (in a form rotation and translation).
How can I achieve this ?

Thanks in advance.

May i also get your email address?

**Comment by SRainGit** [comment]
The code is programmed to work in offline, debug, and step-by-step mode. So, you need to find every needed function feeding to a 'main' function to achieve the end-to-end task. There also should be multi-thread processing. I am not sure if it is too hard for you.
Of course, you can contact me by email: deyu.yin@whu.edu.cn
