### ISSUE TITLE
Which data can be substituted for dirKeyPts3DFeatNet in PoseEstimation.py?

### ISSUE THREAD

**Issue by nanaBaah** [SRainGit/CAE-LO#15]
In the PoseEstimation.py file on line  177 :
`
dirKeyPts3DFeatNet = '/media/rain/Win10_F/KITTI_odometry/output_3DFeatNet/Descriptors/'
`

Which data can I substitute for the dirKeyPts3DFeatNet assuming I am training it on a different data set ?

Also can you please share the features data as well?

Thanks a lot for your help.

**Comment by SRainGit** [comment]
That is for the comparison with 3DFeat-Net. The whole feature data is too large to share. You can check the demo data within the uploaded zip file.
