### ISSUE TITLE
How to plot 3d pointcloud feature matching like figure 6 in your paper?

### ISSUE THREAD

**Issue by LongruiDong** [SRainGit/CAE-LO#18]
Hi，
I want to draw the line between the 3d key points to represent the matching relationship and I found figure 6 in your paper very awesome, So How to plot 3d pointcloud feature matching like that?

Thanks~

**Comment by SRainGit** [comment]
Hi, sorry for the late reply. 
Check out `Scripts/GenerateTrajactory.m` for the visualizing code, which is borrowed from 3DFeat-Net actually.
You can also try `Match.py` (using mayavi), but with a different style.

**Comment by LongruiDong** [comment]
> Hi, sorry for the late reply.
> Check out `Scripts/GenerateTrajactory.m` for the visualizing code, which is borrowed from 3DFeat-Net actually.
> You can also try `Match.py` (using mayavi), but with a different style.

Ok, I will try~
