### ISSUE TITLE
About Interest points and features

### ISSUE THREAD

**Issue by immaturehaan** [SRainGit/CAE-LO#3]
Hello, this project is really awesome. However, I cannot load keypoints and featured because there is no Baidu account. Can you help me by emailing me? Thank you very much.

**Comment by SRainGit** [comment]
Hi, thanks for your interest. The files are too big (several GBs) for emailing. So, I still recommend you to use BaiduNetDisk to download the data as it's easy to install the app and register one account for it.

**Comment by SRainGit** [comment]
> Hello, this project is really awesome. However, I cannot load keypoints and featured because there is no Baidu account. Can you help me by emailing me? Thank you very much.

Hi, thanks for your interest. The files are too big (several GBs) for emailing. So, I still recommend you to use BaiduNetDisk to download the data as it's easy to install the app and register one account for it.

**Comment by immaturehaan** [comment]
Thank you for replying, but it seems that Baidu does not allow creating accounts outside of China. So I cannot create an account and download :<

**Comment by SRainGit** [comment]
Sounds weird. OK, anyway, I will upload some data to GoogleDrive.

**Comment by immaturehaan** [comment]
Hi, I have downloaded the data. However, it cannot be decompressed. I tried removing the tail of numbers but it still reported an error. Can you tell me how you saved this data?
Thank you very much.

**Comment by SRainGit** [comment]
> Hi, I have downloaded the data. However, it cannot be decompressed. I tried removing the tail of numbers but it still reported an error. Can you tell me how you saved this data?
> Thank you very much.

Hi, the tail numbers are the indexes of the volumes. The zip files in the same folder are compressed from the same data source.

As I know, the indexes can be recognized automatically in windows systems when decompressing them. In Linux systems, try to merge them as one file at first.

BTW, I uploaded the interest points and features for 00 and 01 (generated by our method). You can download them from the link:
https://drive.google.com/open?id=1MATZrnTgBXeKmaIyC-x5dRHrZ6hX9Hl0

**Comment by immaturehaan** [comment]
Many thanks ^^
