### ISSUE TITLE
Cannot find the correct installation package for PCLKeypoint

### ISSUE THREAD

**Issue by nanaBaah** [SRainGit/CAE-LO#9]
from the PclKeyPts.py file, the import PCLKeypoint cannot be found.
Which package do I need to install to solve this import error and resolve this issue?

![image](https://user-images.githubusercontent.com/12661590/97455723-7236f780-1938-11eb-95df-4aa34ec22bd8.png)

**Comment by SRainGit** [comment]
The PCLKeyPts was borrowed from here:
https://github.com/lijx10/PCLKeypoints

**Comment by nanaBaah** [comment]
How were you able to import it ? because I encounter errors when trying to.

In the terminal - Ubuntu 18.04 

this is what I do but I still get errors:

`git clone https://github.com/lijx10/PCLKeypoints`
`cd PCLKeypoints\`
`pip3 setup.py install`

In the python code:
I added the path of the "PCLKeypoints/build/lib.linux-x86_64-3.6/PCLKeypoint.cpython-36m-x86_64-linux-gnu.so" file in the 
sys.path.insert(1,'....../PCLKeypoint.cpython-36m-x86_64-linux-gnu.so')

import PCLKeyPoint 

`ImportError: /home//anaconda3/envs/_env3/bin/../lib/libgnutls.so.30: symbol mpn_add_1 version HOGWEED_4 not defined in file libhogweed.so.4 with link time reference
`

**Comment by SRainGit** [comment]
I think it should be `python3 setup.py install`, 
referred from here: https://github.com/lijx10/USIP

**Comment by nanaBaah** [comment]
Thanks for your help.

I realized that its dependent on pcl-1.11.0.
